### ISSUE TITLE
podpora iOS 9.3.5

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/iOS-IIIF-Presenter#1]
Aplikace říká, že funguje jen na iOS 10.2 + a nedá se proto testovat na ipadu mini, který zamrzl na 9.3.5. Je nějaký zásadní důvod proč nepodporovat verzi 9?

**Comment by Fiser33** [comment]
Omezeni na iOS 10.2+ je implicitni pri vytvareni noveho projektu. Pri nahravani na TestFlight jsem na toto nastaveni zapomnel. Jiz jsem pridal podporu od iOS 8.0 a novy build nahral na TestFlight. Dekuji za upozorneni.
