### ISSUE TITLE
hloubka zanoření do kolekcí

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/iOS-IIIF-Presenter#10]
když jsem hlouběji zanořený, hodilo by se vědět kde se nacházím

**Comment by Fiser33** [comment]
Přidána hlavička s názvem aktuální úrovně. Další vývoj zobrazení aktuální úrovně bude probíhat podle issue [#6](https://github.com/moravianlibrary/iOS-IIIF-Presenter/issues/6).
