### ISSUE TITLE
Thumbnail fragment displays instead of a fullscreen page

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/iOS-IIIF-Presenter#3]
![img_0004](https://cloud.githubusercontent.com/assets/811537/24649867/bf50d6c6-1928-11e7-8a6e-0a7de1e3cb7f.PNG)
Při listování svazkem Bůh: Rusky... se občas stane, že se stránka zobrazí tak jako je vidět na obrázku.

**Comment by zabak** [comment]
Dělají to zdá se i všechny knihy z villanova kolekce: např: IIIF universe-> villanova DL-> Dime novel and popular literature -> non-fiction -> ten cent handbooks -> how to do chemical tricks

**Comment by zabak** [comment]
Not limited to ipad mini with ios 9.3.5, same problem on ipad with ios 10.3.1

**Comment by Fiser33** [comment]
Opraveno ve verzi aplikace v1.1.1.
