### ISSUE TITLE
zobrazení náhledů u kolekcí

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/iOS-IIIF-Presenter#4]
Pokud nemá kolekce v současnosti žádný reprezentativní obrázek, tak se zobrazí šedá ploška. Bylo by vhodné na té plošce pokud možno nějaký náhled zobrazit (ono to teď vypadá, jako by to zčásti nefungovalo). Prakticky by to znamenalo v každé položce top-level seznamu jít o level níž, tam vlézt do první nebo nejdříve stažené položky a rekurzivně se takto dostat na první obrázek. Ten pak zobrazit. Obrázky by si aplikace mohla kešovat, případně dělat i nějaký pre-fetching.

**Comment by Fiser33** [comment]
Aplikace nyní (verze 1.0.10) rekurzívně vyhledává náhled pro kolekci v pořadí DFS. Pro cache je vytvořen separátní issue [#14](https://github.com/moravianlibrary/iOS-IIIF-Presenter/issues/14). Toto issue tedy zavírám.
