### ISSUE TITLE
IIIF Universe - počet karet

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/iOS-IIIF-Presenter#7]
Pokud si otevřu IIIF universe, zobrazí se mi napřed 12 karet. ty pak postupně pomizí a zůstane jich 6. Při vícesloupcovém zobrazení to vypadá divoce, když ty karty začnou hned mizet a zbytek poskakuje.

**Comment by Fiser33** [comment]
Opraveno ve verzi 1.0.10. Aplikace nyní položky nezobrazí, dokud nejsou úspěšně načtené. Další požadavky na načítání karet jsou vypsány jako nové issues ([#11](https://github.com/moravianlibrary/iOS-IIIF-Presenter/issues/11) a [#14](https://github.com/moravianlibrary/iOS-IIIF-Presenter/issues/14)).
